version: "3"

services:
  mysql:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "agendamentoemaildb"
    ports: 
      - 3306:3306
    volumes: 
      - /home/thiago/database/mysql:/var/lib/mysql
    networks:
      - mysql-network
  
networks:
  mysql-network:
    driver: bridge